language: java
jdk:
  - openjdk8
cache:
  directories:
    - testdata/pristine
    - $HOME/.m2
before_script: ./scripts/get-pristine
#deploy:
#  provider: script
#  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
#  skip_cleanup: true
#  on:
#    tags: true
