language: java
jdk:
  - openjdk8
install: true
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
after_success:
# Move the code coverage results to codecov
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
cache:
  directories:
    - testdata/pristine
    - $HOME/.m2
before_script: ./scripts/get-pristine
